Fix Bootloop and Optimise Build Procedure.

diff --git a/.github/workflows/build-kernel-release.yml b/.github/workflows/build-kernel-release.yml
--- a/.github/workflows/build-kernel-release.yml
+++ b/.github/workflows/build-kernel-release.yml
@@ -13,38 +13,46 @@ on:
         type: boolean
         default: false
       ksun_branch:
-        description: "Choose KernelSU Next Branch"
+        description: 'Choose KernelSU Next Branch'
         required: true
         type: choice
         options:
           - stable
           - next
         default: next
+      optimize_level:
+        description: "Compiler optimization level"
+        required: true
+        type: choice
+        options:
+          - O2
+          - O3
+        default: O2
       android12-5_10_susfs_branch:
-        description: "Choose SusFS Branch for android12-5.10"
+        description: 'Choose SusFS Branch for android12-5.10'
         type: string
-        default: "gki-android12-5.10"
+        default: 'gki-android12-5.10'
       android13-5_10_susfs_branch:
-        description: "Choose SusFS Branch for android13-5.10"
+        description: 'Choose SusFS Branch for android13-5.10'
         type: string
-        default: "gki-android13-5.10"
+        default: 'gki-android13-5.10'
       android13-5_15_susfs_branch:
-        description: "Choose SusFS Branch for android13-5.15"
+        description: 'Choose SusFS Branch for android13-5.15'
         type: string
-        default: "gki-android13-5.15"
+        default: 'gki-android13-5.15'
       android14-5_15_susfs_branch:
-        description: "Choose SusFS Branch for android14-5.15"
+        description: 'Choose SusFS Branch for android14-5.15'
         type: string
-        default: "gki-android14-5.15"
+        default: 'gki-android14-5.15'
       android14-6_1_susfs_branch:
-        description: "Choose SusFS Branch for android14-6.1"
+        description: 'Choose SusFS Branch for android14-6.1'
         type: string
-        default: "gki-android14-6.1"
+        default: 'gki-android14-6.1'
       android15-6_6_susfs_branch:
-        description: "Choose SusFS Branch for android15-6.6"
+        description: 'Choose SusFS Branch for android15-6.6'
         type: string
-        default: "gki-android15-6.6"
-      
+        default: 'gki-android15-6.6'
+
 jobs:
   build-batch-1:
     name: build-batch-1 (${{ matrix.model }}, ${{ matrix.soc }}, ${{ matrix.branch }}, ${{ matrix.manifest }}, ${{ matrix.android_version }}, ${{ matrix.kernel_version }}, ${{ inputs.ksun_branch }})
@@ -52,67 +60,49 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - model: OP11
-            soc: kalama
-            branch: oneplus/sm8550
-            manifest: oneplus_11_v.xml
-            android_version: android13
-            kernel_version: "5.15"
-          - model: OP11r
-            soc: waipio
-            branch: oneplus/sm8475
-            manifest: oneplus_11r_v.xml
-            android_version: android12
-            kernel_version: "5.10"
-          - model: OP-OPEN
-            soc: kalama
-            branch: oneplus/sm8550
-            manifest: oneplus_open_v.xml
-            android_version: android13
-            kernel_version: "5.15"
-          - model: OP-ACE-2
-            soc: waipio
-            branch: oneplus/sm8475
-            manifest: oneplus_ace2_v.xml
-            android_version: android12
-            kernel_version: "5.10"
-          - model: OP10t
-            soc: waipio
-            branch: oneplus/sm8475
-            manifest: oneplus_10t_v.xml
-            android_version: android12
-            kernel_version: "5.10"
-          - model: OP10pro
-            soc: waipio
-            branch: oneplus/sm8450
-            manifest: oneplus_10_pro_v.xml
-            android_version: android12
-            kernel_version: "5.10"
-          - model: OP-ACE-2-PRO
-            soc: kalama
-            branch: oneplus/sm8550
-            manifest: oneplus_ace2_pro_v.xml
-            android_version: android13
-            kernel_version: "5.15"
-          - model: OP12r
-            soc: kalama
-            branch: oneplus/sm8550
-            manifest: oneplus_12r_v.xml
-            android_version: android13
-            kernel_version: "5.15"
-          - model: OP-Nord-4-CE
-            soc: crow
-            branch: oneplus/sm7550
-            manifest: oneplus_nord_ce4_v.xml
-            android_version: android13
-            kernel_version: "5.15"
+          - model: OP13
+            soc: sun
+            branch: oneplus/sm8750
+            manifest: oneplus_13.xml
+            android_version: android15
+            kernel_version: '6.6'
+          - model: OPAce5Pro
+            soc: sun
+            branch: oneplus/sm8750
+            manifest: oneplus_ace5_pro.xml
+            android_version: android15
+            kernel_version: '6.6'
+          - model: OP13S
+            soc: sun
+            branch: oneplus/sm8750
+            manifest: oneplus_13s.xml
+            android_version: android15
+            kernel_version: '6.6'
+          - model: OP-PAD-3
+            soc: sun
+            branch: oneplus/sm8750
+            manifest: oneplus_pad_3.xml
+            android_version: android15
+            kernel_version: '6.6'
+          - model: OP13T
+            soc: sun
+            branch: oneplus/sm8750
+            manifest: oneplus_13t.xml
+            android_version: android15
+            kernel_version: '6.6'
+          - model: OP-PAD-2-PRO
+            soc: sun
+            branch: oneplus/sm8750
+            manifest: oneplus_pad_2_pro.xml
+            android_version: android15
+            kernel_version: '6.6'
+          
     runs-on: ubuntu-latest
     steps:
       - name: Select Appropriate SusFS Branch
         id: get-susfs-branch
         run: |
           KERNEL_STRING="${{ matrix.android_version }}-${{ matrix.kernel_version }}"
-          
           case "$KERNEL_STRING" in
             "android12-5.10")
               SUSFS_BRANCH="${{ inputs.android12-5_10_susfs_branch }}"
@@ -137,11 +127,9 @@ jobs:
               exit 1
               ;;
           esac
-          
           if [[ -z "$SUSFS_BRANCH" ]]; then
             SUSFS_BRANCH="gki-${{ matrix.android_version }}-${{ matrix.kernel_version }}"
           fi
-          
           echo "susfs_branch=$SUSFS_BRANCH" >> $GITHUB_OUTPUT
 
       - name: Checkout Code
@@ -167,46 +155,40 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - model: OP13
-            soc: sun
-            branch: oneplus/sm8750
-            manifest: oneplus_13.xml
-            android_version: android15
-            kernel_version: "6.6"
-          - model: OPAce5Pro
-            soc: sun
-            branch: oneplus/sm8750
-            manifest: oneplus_ace5_pro.xml
-            android_version: android15
-            kernel_version: "6.6"
           - model: OP12
             soc: pineapple
             branch: oneplus/sm8650
             manifest: oneplus12_v.xml
             android_version: android14
-            kernel_version: "6.1"
+            kernel_version: '6.1'
           - model: OP13r
             soc: pineapple
             branch: oneplus/sm8650
             manifest: oneplus_13r.xml
             android_version: android14
-            kernel_version: "6.1"
+            kernel_version: '6.1'
           - model: OP-ACE-5
             soc: pineapple
             branch: oneplus/sm8650
             manifest: oneplus_ace5.xml
             android_version: android14
-            kernel_version: "6.1"
+            kernel_version: '6.1'
           - model: OP-ACE-3V
             soc: pineapple
             branch: oneplus/sm7675
             manifest: oneplus_ace_3v_v.xml
             android_version: android14
-            kernel_version: "6.1"
+            kernel_version: '6.1'
           - model: OP-NORD-4
             soc: pineapple
             branch: oneplus/sm7675
             manifest: oneplus_nord_4_v.xml
+            android_version: android14
+            kernel_version: '6.1'
+          - model: OP-Nord-5
+            soc: cliffs
+            branch: oneplus/sm8635
+            manifest: oneplus_nord_5.xml
             android_version: android14
             kernel_version: "6.1"
           - model: OP-PAD-2
@@ -214,62 +196,31 @@ jobs:
             branch: oneplus/sm8650
             manifest: oneplus_pad2_v.xml
             android_version: android14
-            kernel_version: "6.1"
-          - model: OP13S
-            soc: sun
-            branch: oneplus/sm8750
-            manifest: oneplus_13s.xml
-            android_version: android15
-            kernel_version: "6.6"
+            kernel_version: '6.1'
           - model: OP-Ace3-Pro
             soc: pineapple
             branch: oneplus/sm8650
             manifest: oneplus_ace3_pro_v.xml
             android_version: android14
-            kernel_version: "6.1"
-          - model: OP-PAD-3
-            soc: sun
-            branch: oneplus/sm8750
-            manifest: oneplus_pad_3.xml
-            android_version: android15
-            kernel_version: "6.6"
-          - model: OP13T
-            soc: sun
-            branch: oneplus/sm8750
-            manifest: oneplus_13t.xml
-            android_version: android15
-            kernel_version: "6.6"
-          - model: OP-PAD-2-PRO
-            soc: sun
-            branch: oneplus/sm8750
-            manifest: oneplus_pad_2_pro.xml
-            android_version: android15
-            kernel_version: "6.6"
-          - model: OP-PAD-Pro
-            soc: pineapple
-            branch: oneplus/sm8650
-            manifest: oneplus_pad_pro_v.xml
-            android_version: android14
-            kernel_version: "6.1"
-          - model: OP-Nord-5
-            soc: cliffs
-            branch: oneplus/sm8635
-            manifest: oneplus_nord_5.xml
-            android_version: android14
-            kernel_version: "6.1"
+            kernel_version: '6.1'
           - model: OP-Nord-CE4-LITE
             soc: blair
             branch: oneplus/sm6375
             manifest: oneplus_nord_ce4_lite_5g_v.xml
             android_version: android14
             kernel_version: "6.1"
+          - model: OP-PAD-Pro
+            soc: pineapple
+            branch: oneplus/sm8650
+            manifest: oneplus_pad_pro_v.xml
+            android_version: android14
+            kernel_version: '6.1'
     runs-on: ubuntu-latest
     steps:
       - name: Select Appropriate SusFS Branch
         id: get-susfs-branch
         run: |
           KERNEL_STRING="${{ matrix.android_version }}-${{ matrix.kernel_version }}"
-          
           case "$KERNEL_STRING" in
             "android12-5.10")
               SUSFS_BRANCH="${{ inputs.android12-5_10_susfs_branch }}"
@@ -294,11 +245,121 @@ jobs:
               exit 1
               ;;
           esac
-          
           if [[ -z "$SUSFS_BRANCH" ]]; then
             SUSFS_BRANCH="gki-${{ matrix.android_version }}-${{ matrix.kernel_version }}"
           fi
-          
+          echo "susfs_branch=$SUSFS_BRANCH" >> $GITHUB_OUTPUT
+
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 1
+
+      - name: Build Kernel
+        uses: ./.github/actions
+        with:
+          model: ${{ matrix.model }}
+          soc: ${{ matrix.soc }}
+          branch: ${{ matrix.branch }}
+          manifest: ${{ matrix.manifest }}
+          android_version: ${{ matrix.android_version }}
+          kernel_version: ${{ matrix.kernel_version }}
+          ksun_branch: ${{ inputs.ksun_branch }}
+          susfs_branch: ${{ steps.get-susfs-branch.outputs.susfs_branch }}
+
+  build-batch-3:
+    name: build-batch-3 (${{ matrix.model }}, ${{ matrix.soc }}, ${{ matrix.branch }}, ${{ matrix.manifest }}, ${{ matrix.android_version }}, ${{ matrix.kernel_version }}, ${{ inputs.ksun_branch }})
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - model: OP11
+            soc: kalama
+            branch: oneplus/sm8550
+            manifest: oneplus_11_v.xml
+            android_version: android13
+            kernel_version: '5.15'
+          - model: OP11r
+            soc: waipio
+            branch: oneplus/sm8475
+            manifest: oneplus_11r_v.xml
+            android_version: android12
+            kernel_version: '5.10'
+          - model: OP-OPEN
+            soc: kalama
+            branch: oneplus/sm8550
+            manifest: oneplus_open_v.xml
+            android_version: android13
+            kernel_version: '5.15'
+          - model: OP-ACE-2
+            soc: waipio
+            branch: oneplus/sm8475
+            manifest: oneplus_ace2_v.xml
+            android_version: android12
+            kernel_version: '5.10'
+          - model: OP10t
+            soc: waipio
+            branch: oneplus/sm8475
+            manifest: oneplus_10t_v.xml
+            android_version: android12
+            kernel_version: '5.10'
+          - model: OP-Nord-4-CE
+            soc: crow
+            branch: oneplus/sm7550
+            manifest: oneplus_nord_ce4_v.xml
+            android_version: android13
+            kernel_version: "5.15"
+          - model: OP10pro
+            soc: waipio
+            branch: oneplus/sm8450
+            manifest: oneplus_10_pro_v.xml
+            android_version: android12
+            kernel_version: '5.10'
+          - model: OP-ACE-2-PRO
+            soc: kalama
+            branch: oneplus/sm8550
+            manifest: oneplus_ace2_pro_v.xml
+            android_version: android13
+            kernel_version: '5.15'
+          - model: OP12r
+            soc: kalama
+            branch: oneplus/sm8550
+            manifest: oneplus_12r_v.xml
+            android_version: android13
+            kernel_version: '5.15'          
+    runs-on: ubuntu-latest
+    steps:
+      - name: Select Appropriate SusFS Branch
+        id: get-susfs-branch
+        run: |
+          KERNEL_STRING="${{ matrix.android_version }}-${{ matrix.kernel_version }}"
+          case "$KERNEL_STRING" in
+            "android12-5.10")
+              SUSFS_BRANCH="${{ inputs.android12-5_10_susfs_branch }}"
+              ;;
+            "android13-5.10")
+              SUSFS_BRANCH="${{ inputs.android13-5_10_susfs_branch }}"
+              ;;
+            "android13-5.15")
+              SUSFS_BRANCH="${{ inputs.android13-5_15_susfs_branch }}"
+              ;;
+            "android14-5.15")
+              SUSFS_BRANCH="${{ inputs.android14-5_15_susfs_branch }}"
+              ;;
+            "android14-6.1")
+              SUSFS_BRANCH="${{ inputs.android14-6_1_susfs_branch }}"
+              ;;
+            "android15-6.6")
+              SUSFS_BRANCH="${{ inputs.android15-6_6_susfs_branch }}"
+              ;;
+            *)
+              echo "Invalid kernel version or unsupported: $KERNEL_STRING"
+              exit 1
+              ;;
+          esac
+          if [[ -z "$SUSFS_BRANCH" ]]; then
+            SUSFS_BRANCH="gki-${{ matrix.android_version }}-${{ matrix.kernel_version }}"
+          fi
           echo "susfs_branch=$SUSFS_BRANCH" >> $GITHUB_OUTPUT
 
       - name: Checkout Code
@@ -322,20 +383,20 @@ jobs:
     needs:
       - build-batch-1
       - build-batch-2
+      - build-batch-3
     runs-on: ubuntu-latest
     if: ${{ inputs.make_release }}
     env:
       REPO_OWNER: ${{ github.repository_owner }}
       REPO_NAME: ${{ github.event.repository.name }}
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      RELEASE_NAME: "*TEST BUILD* OnePlus Kernels With KernelSU Next & SUSFS v1.5.9 *TEST BUILD*"
-
+      RELEASE_NAME: 'TEST BUILD OnePlus Kernels With KernelSU Next & SUSFS v1.5.9 TEST BUILD'
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           fetch-depth: 1
-
+          
       - name: Generate and Create New Tag
         run: |
           BASE_TAG="v1.5.9-r0"
